SELECT USER
  FROM DUAL;
  
SELECT TBL_MEMBER;

DROP TABLE TBL_SCORE PURGE;
--==>> Table TBL_SCORE이(가) 삭제되었습니다.


--○ 실습 테이블 생성
CREATE TABLE TBL_SCORE
( SID   NUMBER
, NAME  VARCHAR2(30)
, KOR   NUMBER(3)
, ENG   NUMBER(3)
, MAT   NUMBER(3)
);
--==>> Table TBL_SCORE이(가) 생성되었습니다.


--○ 생성된 테이블에 제약조건 추가
ALTER TABLE TBL_SCORE
ADD CONSTRAINT SCORE_SID_PK PRIMARY KEY(SID);
--==>> Table TBL_SCORE이(가) 변경되었습니다.

ALTER TABLE TBL_SCORE
ADD CONSTRAINT SCORE_KOR_CK CHECK(KOR BETWEEN 0 AND 100);
--==>> Table TBL_SCORE이(가) 변경되었습니다.

ALTER TABLE TBL_SCORE
ADD CONSTRAINT SCORE_ENG_CK CHECK(ENG BETWEEN 0 AND 100);

ALTER TABLE TBL_SCORE
ADD CONSTRAINT SCORE_MAT_CK CHECK(MAT BETWEEN 0 AND 100);


DROP SEQUENCE SCORESEQ;

CREATE SEQUENCE SCORESEQ
NOCACHE;

SELECT SID, NAME, KOR, ENG, MAT
     , (KOR+ENG+MAT) AS TOT
     , (KOR+ENG+MAT)/3 AS AVG
FROM TBL_SCORE
ORDER BY SID;

SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT, (KOR+ENG+MAT)/3 AS AVG FROM TBL_SCORE ORDER BY SID
;

--○ 데이터 입력 쿼리문 구성
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT)
VALUES(SCORESEQ.NEXTVAL, '박현수', 90, 80, 70);
-->
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '박현수', 90, 80, 70)
;
--==>> 1 행 이(가) 삽입되었습니다.
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '임소민', 80, 70, 60)
;
--==>> 1 행 이(가) 삽입되었습니다.
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '우수정', 70, 60, 50)
;
--==>> 1 행 이(가) 삽입되었습니다.

SELECT COUNT(*) AS COUNT
  FROM TBL_SCORE;
SELECT COUNT(*) AS COUNT  FROM TBL_SCORE
;

--○ 확인
SELECT *
FROM TBL_SCORE;
--==>>
/*
1	박현수	90	80	70
2	임소민	80	70	60
3	우수정	70	60	50
*/


--○ 커밋
COMMIT;







